### ISSUE TITLE
🐛 [Cloud Run] - Deployment doesn't create new revision 

### ISSUE THREAD

**Issue by jeanphi-baconnais** [GoogleCloudBuild/cicd-images#37]
## Expected Behavior

This command  creates new revision for the service quoted.
```yaml
cloud-run deploy --project-id "$[[ inputs.project_id ]]" --service "$[[ inputs.service ]]" --region "$[[ inputs.region ]]" --google-apis-user-agent "google-gitlab-components:deploy-cloud-run/$COMPONENT_VERSION" \
      "${ARGS[@]}"
```

## Actual Behavior

The command doesn't create new revision if the service already exists.

## Steps to Reproduce the Problem

1. I have a GitLab Project
2. Including the CICD Catalaog
```yaml
include:
  - component: $CI_SERVER_FQDN/google-gitlab-components/cloud-run/deploy-cloud-run@0.2.0
    inputs:
      project_id: $GCLOUD_PROJECT_ID
      service: $GCLOUD_SERVICE_ID
      region: $GCLOUD_REGION
      source: "."
      stage: "deploy"
      as: "🚀 deploy-to-cloud-run"
```

4. Run the pipeline with the correct arguments 

The job success, we can see this type of log : `2024/11/07 10:36:14 Service [api-commu-nantes] with revision [api-commu-nantes-00005-gft] is deployed successfully, serving 100 percent of traffic.` but in my example the api-commu-nantes-00005-gft revision is not a new one.

Maybe I don't understand one point but I imagine a new revision will be created?
